! only require mockito-core instead of -all
This avoids classpath conflicts that result in
“NoSuchMethodError: org.hamcrest.Matcher.describeMismatch”
http://stackoverflow.com/questions/7869711

mockito-all brings its own hamcrest.